import { useMemo, useState } from 'react';
import type { LeafletMouseEvent } from 'leaflet';
import { ConnectionBadge } from './components/ConnectionBadge';
import MapPanel from './components/MapPanel';
import { MissionPanel } from './components/MissionPanel';
import { ResourcesPanel } from './components/ResourcesPanel';
import { TelemetryPanel } from './components/TelemetryPanel';
import { TemporaryEsp32StatusPanel } from './components/TemporaryEsp32StatusPanel';
import { useMissionSocket } from './hooks/useMissionSocket';
import type { LatLng } from './types';

const DEFAULT_CENTER: LatLng = { lat: 13.0827, lng: 80.2707 };

export default function App() {
  const [boundaryPoints, setBoundaryPoints] = useState<LatLng[]>([]);
  const [fieldLocked, setFieldLocked] = useState(false);
  const [payload, setPayload] = useState('IRRIGATION');
  const [dose, setDose] = useState('0');
  const [spacing, setSpacing] = useState('0');
  const [rowSpacing, setRowSpacing] = useState('1.0');
  const [samplingSpacing, setSamplingSpacing] = useState('3.0');
  const [localError, setLocalError] = useState<string | null>(null);
  const { connected, missionPlan, telemetry, error, startMission, stopMission, resetMission } = useMissionSocket();
  const resources = telemetry?.resources_used ?? { fertilizer_g: 0, water_ml: 0, seeds: 0 };
  const mapCenter = useMemo(() => boundaryPoints[0] ?? DEFAULT_CENTER, [boundaryPoints]);
  const missionState = telemetry?.rover_status ?? (missionPlan ? 'MISSION READY' : fieldLocked ? 'SUBMITTING' : 'FIELD SETUP');
  const displayedRowSpacing = missionPlan?.row_spacing_m ?? (Number(rowSpacing) || 1.0);
  const displayedSamplingSpacing = missionPlan?.sampling_density_m ?? (Number(samplingSpacing) || 3.0);

  const handleMapClick = (event: LeafletMouseEvent) => {
    if (fieldLocked) return;
    setBoundaryPoints((points) => [...points, { lat: event.latlng.lat, lng: event.latlng.lng }]);
    setLocalError(null);
  };

  const handleStart = () => {
    if (boundaryPoints.length < 3) { setLocalError('Select at least three boundary points before starting.'); return; }
    const requestedRowSpacing = Number(rowSpacing);
    const requestedSamplingSpacing = Number(samplingSpacing);
    if (!Number.isFinite(requestedRowSpacing) || requestedRowSpacing <= 0 || !Number.isFinite(requestedSamplingSpacing) || requestedSamplingSpacing <= 0) {
      setLocalError('Row spacing and sampling spacing must both be greater than zero.');
      return;
    }
    setFieldLocked(true);
    const sent = startMission(boundaryPoints, payload, { dose_grams: Number(dose) || 0, spacing_m: Number(spacing) || 0 }, requestedRowSpacing, requestedSamplingSpacing);
    if (!sent) setFieldLocked(false);
  };

  const reset = () => { stopMission(); resetMission(); setBoundaryPoints([]); setFieldLocked(false); setLocalError(null); };
  const visibleError = localError ?? error;

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-glyph">AR</div><div><strong>AgriRover</strong><span>Precision field operations</span></div></div><div className="topbar-right"><span className="session-label">CONTROL ROOM / 01</span><ConnectionBadge connected={connected} /></div></header>
    <main className="dashboard">
      <section className="intro"><div><span className="eyebrow">Autonomous mission control</span><h1>Field operations, <em>in view.</em></h1><p>Define a boundary, dispatch the rover, and monitor every pass from one calm workspace.</p></div><div className="mission-state"><span className="state-kicker">Current state</span><strong>{missionState}</strong><span className="state-line" /></div></section>
      {visibleError && <div className="alert" role="alert"><span className="alert-icon">!</span><span>{visibleError}</span><button onClick={() => setLocalError(null)} aria-label="Dismiss error">×</button></div>}
      <section className="workspace">
        <div className="map-column"><div className="map-frame"><div className="map-toolbar"><div><span className="eyebrow">Field canvas</span><strong>{boundaryPoints.length ? `${boundaryPoints.length} boundary points` : 'Click to define your field'}</strong></div><span className="map-legend"><i className="legend-field" /> boundary <i className="legend-route" /> route <i className="legend-rover" /> rover</span></div><MapPanel boundaryPoints={boundaryPoints} missionPlan={missionPlan} telemetry={telemetry} onMapClick={handleMapClick} center={mapCenter} /><div className="map-footer"><span>Rows: {displayedRowSpacing} m</span><span>Sampling: {displayedSamplingSpacing} m</span><span>Coverage generated by backend</span></div></div>
          <div className="control-bar"><div className="control-fields"><label>Active payload<select value={payload} onChange={(event) => setPayload(event.target.value)} disabled={fieldLocked}><option>IRRIGATION</option><option>SEEDING</option><option>FERTILIZER</option></select></label><label>Row spacing<input type="number" min="0.1" step="0.1" value={rowSpacing} onChange={(event) => setRowSpacing(event.target.value)} disabled={fieldLocked} /><small>meters</small></label><label>Sampling spacing<input type="number" min="0.1" step="0.1" value={samplingSpacing} onChange={(event) => setSamplingSpacing(event.target.value)} disabled={fieldLocked} /><small>meters</small></label><label>Prescription dose<input type="number" min="0" value={dose} onChange={(event) => setDose(event.target.value)} disabled={fieldLocked} /><small>grams</small></label><label>Payload spacing<input type="number" min="0" value={spacing} onChange={(event) => setSpacing(event.target.value)} disabled={fieldLocked} /><small>meters</small></label></div><div className="control-actions"><button className="button ghost" onClick={reset}>Reset field</button><button className="button primary" onClick={handleStart} disabled={fieldLocked}>{fieldLocked ? 'Mission active' : 'Start mission'}<span>→</span></button></div></div>
          <TemporaryEsp32StatusPanel telemetry={telemetry} />
        </div>
        <aside className="side-column"><MissionPanel plan={missionPlan} /><TelemetryPanel telemetry={telemetry} /><ResourcesPanel resources={resources} /></aside>
      </section>
    </main>
    <footer><span>AGR • AUTONOMOUS GROUND ROBOTICS</span><span>System telemetry is advisory. Hardware safety controls remain local.</span></footer>
  </div>;
}
