import { useMemo, useState } from 'react';
import { LoadScript } from '@react-google-maps/api';
import { ConnectionBadge } from './components/ConnectionBadge';
import MapPanel from './components/MapPanel';
import { MissionPanel } from './components/MissionPanel';
import { ResourcesPanel } from './components/ResourcesPanel';
import { TelemetryPanel } from './components/TelemetryPanel';
import { useMissionSocket } from './hooks/useMissionSocket';
import type { LatLng } from './types';

const API_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY as string | undefined;
const DEFAULT_CENTER: LatLng = { lat: 13.0827, lng: 80.2707 };

export default function App() {
  const [boundaryPoints, setBoundaryPoints] = useState<LatLng[]>([]);
  const [fieldLocked, setFieldLocked] = useState(false);
  const [payload, setPayload] = useState('IRRIGATION');
  const [dose, setDose] = useState('0');
  const [spacing, setSpacing] = useState('0');
  const [localError, setLocalError] = useState<string | null>(null);
  const { connected, missionPlan, telemetry, error, startMission, stopMission } = useMissionSocket();
  const resources = telemetry?.resources_used ?? { fertilizer_g: 0, water_ml: 0, seeds: 0 };
  const mapCenter = useMemo(() => boundaryPoints[0] ?? DEFAULT_CENTER, [boundaryPoints]);
  const missionState = telemetry?.rover_status ?? (missionPlan ? 'MISSION READY' : fieldLocked ? 'SUBMITTING' : 'FIELD SETUP');

  const handleMapClick = (event: google.maps.MapMouseEvent) => {
    if (fieldLocked || !event.latLng) return;
    setBoundaryPoints((points) => [...points, { lat: event.latLng!.lat(), lng: event.latLng!.lng() }]);
    setLocalError(null);
  };

  const handleStart = () => {
    if (boundaryPoints.length < 3) { setLocalError('Select at least three boundary points before starting.'); return; }
    setFieldLocked(true);
    const sent = startMission(boundaryPoints, payload, { dose_grams: Number(dose) || 0, spacing_m: Number(spacing) || 0 });
    if (!sent) setFieldLocked(false);
  };

  const reset = () => { stopMission(); setBoundaryPoints([]); setFieldLocked(false); setLocalError(null); };
  const visibleError = localError ?? error;

  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-glyph">AR</div><div><strong>AgriRover</strong><span>Precision field operations</span></div></div><div className="topbar-right"><span className="session-label">CONTROL ROOM / 01</span><ConnectionBadge connected={connected} /></div></header>
    <main className="dashboard">
      <section className="intro"><div><span className="eyebrow">Autonomous mission control</span><h1>Field operations, <em>in view.</em></h1><p>Define a boundary, dispatch the rover, and monitor every pass from one calm workspace.</p></div><div className="mission-state"><span className="state-kicker">Current state</span><strong>{missionState}</strong><span className="state-line" /></div></section>
      {visibleError && <div className="alert" role="alert"><span className="alert-icon">!</span><span>{visibleError}</span><button onClick={() => setLocalError(null)} aria-label="Dismiss error">×</button></div>}
      <section className="workspace">
        <div className="map-column"><div className="map-frame"><div className="map-toolbar"><div><span className="eyebrow">Field canvas</span><strong>{boundaryPoints.length ? `${boundaryPoints.length} boundary points` : 'Click to define your field'}</strong></div><span className="map-legend"><i className="legend-field" /> boundary <i className="legend-route" /> route <i className="legend-rover" /> rover</span></div>{API_KEY ? <LoadScript googleMapsApiKey={API_KEY}><MapPanel boundaryPoints={boundaryPoints} missionPlan={missionPlan} telemetry={telemetry} onMapClick={handleMapClick} center={mapCenter} /></LoadScript> : <div className="map-missing"><span className="map-missing-icon">⌖</span><strong>Google Maps needs a key</strong><span>Add <code>VITE_GOOGLE_MAPS_API_KEY</code> to <code>.env.local</code> to enable field selection.</span></div>}<div className="map-footer"><span>Rows: 1.0 m</span><span>Sampling: 3.0 m</span><span>Coverage generated by backend</span></div></div>
          <div className="control-bar"><div className="control-fields"><label>Active payload<select value={payload} onChange={(event) => setPayload(event.target.value)} disabled={fieldLocked}><option>IRRIGATION</option><option>SEEDING</option><option>FERTILIZER</option></select></label><label>Prescription dose<input type="number" min="0" value={dose} onChange={(event) => setDose(event.target.value)} disabled={fieldLocked} /><small>grams</small></label><label>Spacing<input type="number" min="0" value={spacing} onChange={(event) => setSpacing(event.target.value)} disabled={fieldLocked} /><small>meters</small></label></div><div className="control-actions"><button className="button ghost" onClick={reset}>Reset field</button><button className="button primary" onClick={handleStart} disabled={fieldLocked || !API_KEY}>{fieldLocked ? 'Mission active' : 'Start mission'}<span>→</span></button></div></div>
        </div>
        <aside className="side-column"><MissionPanel plan={missionPlan} /><TelemetryPanel telemetry={telemetry} /><ResourcesPanel resources={resources} /></aside>
      </section>
    </main>
    <footer><span>AGR • AUTONOMOUS GROUND ROBOTICS</span><span>System telemetry is advisory. Hardware safety controls remain local.</span></footer>
  </div>;
}
